### ISSUE TITLE
Finetuning Command for RESISC-45 Downstream Dataset

### ISSUE THREAD

**Issue by AkshitSharma1** [techmn/satmae_pp#5]
Hello!
Thank you for sharing the code and the impressive results.

Will it be possible for you to please share the exact command involving main_finetune.py that has been used to finetune ViT-L on the RESISC-45 downstream dataset?

Thanks
Akshit

**Comment by techmn** [comment]
```
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python -m torch.distributed.launch --nproc_per_node=8 --master_port=29202 main_finetune.py \
--batch_size 8 --accum_iter 16 \
--epochs 50 --warmup_epochs 5 \
--input_size 224 --patch_size 16 \
--model_type vanilla \
--dataset_type resisc \
--nb_classes 45 \
--weight_decay 0.05 --drop_path 0.2 --reprob 0.25 --mixup 0.8 --cutmix 1.0 \
--lr 0.001 --num_workers 16 \
--base_path /datasets/RESISC45/Images/ \
--train_path /datasets/RESISC45/train-resisc.txt \
--test_path /datasets/RESISC45/val-resisc.txt \
--output_dir ./finetune_dir \
--log_dir ./finetune_dir \
--finetune ./output_dir/checkpoint-799.pth
```

**Comment by hubery1619** [comment]
Thank you for sharing the code and for your impressive work! I have a question: when fine-tuning the model on the downstream RESISC45 dataset, are the pretrained weights derived from the pretraining phase on fMoW-RGB, or are they the fine-tuned weights of fMoW-RGB after pretraining? Thank you!

**Comment by techmn** [comment]
Hi,

For all finetuning experiments, we utilize the weights of pre-training either on fMoW-RGB or fMoW-Sentinel. 
In case of RESISC, pre-training weights of fMoW-RGB are used.

Thanks.
