### ISSUE TITLE
Finetuning on EuroSAT and UCMerced Datasets

### ISSUE THREAD

**Issue by AkshitSharma1** [techmn/satmae_pp#6]
Hello!
Thank you for sharing the code and the impressive results.

Will it be possible for you to please share the exact command involving main_finetune.py that has been used to finetune ViT-L on the EuroSAT and UCMerced downstream dataset?

Thanks a lot for your help,
Akshit

**Comment by techmn** [comment]
For EuroSAT (RGB)

```
CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7 python -m torch.distributed.launch --nproc_per_node=8 --master_port=29202 main_finetune.py \
--batch_size 8 --accum_iter 16 \
--epochs 50 --warmup_epochs 5 \
--input_size 224 --patch_size 16 \
--model_type vanilla \
--dataset_type euro_sat \
--nb_classes 10 \
--weight_decay 0.05 --drop_path 0.2 --reprob 0.25 --mixup 0.8 --cutmix 1.0 \
--lr 0.001 --num_workers 16 \
--base_path /datasets/Eurosat/2750/ \
--train_path /datasets/Eurosat/eurosat-train.txt \
--test_path /datasets/Eurosat/eurosat-val.txt \
--output_dir ./finetune_dir \
--log_dir ./finetune_dir \
--finetune ./output_dir/checkpoint-799.pth
```

For UCMerced, update following variables:
```
--base_path  /datasets/...... \
--train_path  /datasets/...... \
--test_path  /datasets/...... \
--dataset_type ucmerced \
--nb_classes 21
```

**Comment by kzigzag** [comment]
Hi, Your work is pretty interesting. Currently, the link for the dataset split txt file could not be accessed by the https as follows:
list_file = {
EuroSAT
https://storage.googleapis.com/remote_sensing_representations/eurosat-train.txt
https://storage.googleapis.com/remote_sensing_representations/eurosat-val.txt
https://storage.googleapis.com/remote_sensing_representations/eurosat-test.txt

UC Merced
https://storage.googleapis.com/remote_sensing_representations/uc_merced-train.txt
https://storage.googleapis.com/remote_sensing_representations/uc_merced-val.txt
https://storage.googleapis.com/remote_sensing_representations/uc_merced-test.txt

BigEarthNet
https://storage.googleapis.com/remote_sensing_representations/bigearthnet-train.txt
https://storage.googleapis.com/remote_sensing_representations/bigearthnet-val.txt
https://storage.googleapis.com/remote_sensing_representations/bigearthnet-test.txt
}
I wonder if you could share them. Thanks so much.
